
before_script:
  # Run ssh-agent (inside the build environment)
  - eval $(ssh-agent -s)
  # annoyingly, there are a bunch of windows return characters in this env var (a gitlab bug)
  # extra annoyingly, a tmp file is needed - can't get a pipe to perl to work inside the ssh-add line
  - echo "$gitlab_to_github_deploy_key" | perl -pi -e 's/\r\n/\n/g' > ./deploykey
  # following line set up in the way it is to avoid an extra chmod step
  - ssh-add <(cat ./deploykey )
  # quick, get rid of it!
  - rm -f ./deploykey
  # test docker is running
  - docker info
  # log into the docker registry
  -  docker login -e unknown -u gitlab-ci-token -p $CI_BUILD_TOKEN bigr.bios.cf.ac.uk:4567
  

types:
  - build
  - deploy

build_app:
  type: build
  script: 
   - make build

deploy_app:
  type: deploy
  script:
   - docker push bigr.bios.cf.ac.uk:4567/sacim/centos7-tl
   - git clone git@bigr:sacim/centos7-tl && cd centos7-tl && git push -f git@github.com:sglim2/docker-centos7-tl master && cd .. && rm -rf centos7-tl


